### ISSUE TITLE
Discussion: FROST-Server and TimescaleDB

### ISSUE THREAD

**Issue by scottlimmer** [FraunhoferIOSB/FROST-Server#105]
Wondering if anyone has had any thoughts on the feasibility of adding [TimescaleDB](https://docs.timescale.com/v1.1/introduction) to the FROST-Server schema; the observations tables being the obvious candidate. 

I've trialled TimescaleDB on a custom Postgres schema and found the performance to be exponentially better than a traditional database (80M row dataset). 

I think there'd be benefits in converting the observations table into a [hypertable](https://docs.timescale.com/v1.1/using-timescaledb/hypertables) however I think code review would be required to get the most out of TimescaleDB and its additional [time-based functions](https://docs.timescale.com/v1.1/api)

**Comment by hylkevds** [comment]
Timescale came up recently here as well, but we've not had time to look into it.
Have you tried turning the Observations table into a hypertable?
It would be good to know if:
- It can be done without any changes to the FROST source
- What the performance increase is for different queries (insert, update, delete & get, with and without the appropriate indices)
- What changes to FROST should be made to get the most out of Timescale

**Comment by riedel** [comment]
My feeling is that this makes only sense if FROST could expose some aggregate queries based on time series (see #26), which is outside of the standard.

Particularly a function like time_bucket_gapfill() would be of high value to anyone who wants implement a decent scalable web interface based on SensorThings.

**Comment by hylkevds** [comment]
In the HERACLES project we store and visualise 100Hz data. By now we have nearly two years of data for three 100 Hz accelerometers, and four 40Hz sensors.
You can have a look at the graphs at: https://heracles-kb.server.de/servlet/is/6679/

You are right that aggregates are required to make this work, but there is no need to have this in the API. In almost all our use cases we calculate aggregates using an external tool (https://github.com/hylkevds/SensorThingsProcessor), that pushes the aggregate data back into FROST as a MultiDatastream with Average, Min, Max and Std-dev. Using this it is already trivial to build a decent scalable web interface based on SensorThings.

The problem with making aggregate functions part of the standard is that there are many ways to calculate aggregates, that depend on the exact sampling regime of the sensor. Simply taking the mathematical average of the numbers may work for sensors with a fixed sampling interval, but will not give sensible values in many other cases.

**Comment by chenkianwee** [comment]
Hi I have been working on a database project for my laboratory. In our lab, we build our own sensors and distribute it across campus. I realise the database will benefit greatly from adopting the sensorthings api. As mentioned above, I am also interested to integrate timescaledb with the sensorthings data model (especially the observations table). 

I have tried to convert the observations table into a hypertable (timescaledb) but it failed as timescaledb requires the primary key to be a timestamp column. I was planning to use the result_time column. However, the observations table uses the id column as the primary key.

As mentioned in hylkevds post it is not required to integrate aggregate functions into the API, which is also not in the standard. However, I thought converting the observations table to hypertable will benefit the backend in maintaining the database and also in exploring the data locally, it might also help with the performance when ingesting and updating data. 

It is possible to export the data and perform explorations on the data externally (e.g. in the case of using timescaledb, copy the observations table and migrate it to a hypertable and perform explorations ). It is an extra step, I thought it might be good if the frost-server can provide the option to convert the observations table into a hypertable. Just some thoughts on the subject.

Thus, one of my question is, instead of the id as primary key, is it possible to use a timestamp column as key , how will that affect the performance of frost-server.

**Comment by riedel** [comment]
@limond sucessfully adopted timescale DB below frost for us with considerable speed up. We should document our index setup ( @johannes-riesterer )

**Comment by hylkevds** [comment]
That timescaledb forces the primary key to be the time column surprises me greatly. That makes it useless for any application that gathers data from multiple sources, as a time collision is guaranteed to happen eventually... Unless the restriction is that the time column has to be a _part_ of the primary key, and you can make it a combined PK of the time with another column.

That said, FROST doesn't really care what the DB thinks is the primary key, as long as the ID column is unique. So you are free to change the PK to whatever you see fit, and FROST won't complain until there is a PK violation and the insert fails.

**Comment by chenkianwee** [comment]
thanks for the reply. @hylkevds I think it is the case that time column has to be a part of the primary key and you can use another column (https://docs.timescale.com/latest/using-timescaledb/schema-management#indexing-best-practices). But I am not sure, I am new and exploring the implementation of these software stacks. 

@riedel it will be useful to see how you guys integrated timescaledb. Thanks. Do let me know where I can reference your integration.

**Comment by riedel** [comment]
@chenkianwee you can find our deployment here: https://github.com/SmartAQnet/smartaqnet-infrastructure/tree/cluster-dev

**Comment by limond** [comment]
@riedel @chenkianwee I was mentioned above, so I would like to add a few words despite me no longer working for TECO.
The README in the repository is probably outdated since I extensively documented the setup and maintenance in the project's internal wiki.
It might help to release these wiki pages and add them to the repository.
However, the index and hypertable setup in use can be found here: https://github.com/SmartAQnet/smartaqnet-infrastructure/blob/cluster-dev/dev/dev-databases/prepare_hypertable.sql

**Comment by riedel** [comment]
Thanks @limond, good to hear from you (I was just was about to post the sql file after looking for it myself)
> The README in the repository is probably outdated since I extensively documented the setup and maintenance in the project's internal wiki.

I just asked @johannes-riesterer to merge the documentation back, but I think there is not much more on the index/hypertable setup part except for this quote

>The preparation differs from the original FROST instructions. The postgis server uses a TimescaleDB instance. In order to initialize the database correctly, point your DOCKER_HOST to the writable worker. Search for the container id of the postgis container (docker ps). You can >execute psql commands like this: docker exec -it <Container ID> psql [...]
>Go into the /dev/dev-databases directory of the repository.
>Execute the following commands:
>      docker exec -it <Container ID> psql --username=sensorthings < globals.sql
>      docker exec -it <Container ID> psql --username=sensorthings < schema.sql
>      docker exec -it <Container ID> psql --username=sensorthings < prepare_hypertable.sql

>These will create and configure database users (globals.sql), the schema of all tables but Observations (schema.sql) and the Observations table as a TimescaleDB hypertable (prepare_hypertable.sql).

**Comment by chenkianwee** [comment]
Thanks @limond and @riedel , this is very helpful !! I had a quick look at the information, looks like shld be enough information for my setup. Thanks again.
