### ISSUE TITLE
String ID in MQTT Topic

### ISSUE THREAD

**Issue by ChrisMalewski** [FraunhoferIOSB/FROST-Server#1119]
Dear developer team,

when we specify an MQTT topic to push observations from an IoT device, we configure the numeric datastream.id off that specific datastream in the topic e.g. v1.1/Datastreams(74)/Observations

Is it possible to also configure the datastream.name or any kind of string encoded id?

Thanks in advance

**Comment by mjacoby** [comment]
If you want to use a different MQTT topic than `v1.1/Datastreams([id])/Observations` to publish new observations, e.g. `v1.1/Datastreams([datastream.name])/Observations` then this is not possible (see [relevant section of the specification](https://docs.ogc.org/is/18-088/18-088.html#create-mqtt-publish)).

If you want to use string-based IDs instead of numeric ones, than yes, this is possible with FROST by setting the config property `plugins.coreModel.idType` ([see documentation](https://fraunhoferiosb.github.io/FROST-Server/settings/plugins.html)). However, this changes the datatype of the `id` property everywhere, i.e. also in HTTP request you'll have to use `'` like v1.1/Datastream('exampleID').

Publishing observations to a datastream identified not by ID but by other means (e.g. custom properties) is currently not supported. The suggested workaround would be to lookup the corresponding datastream ID (e.g. on startup of your software/sensor) and the publish via the URL as you are currently using.

**Comment by ChrisMalewski** [comment]
Dear Michael,
thanks for your explanation.
