### ISSUE TITLE
Unable to use spatial query filters on Datastream/ObservedArea

### ISSUE THREAD

**Issue by scottlimmer** [FraunhoferIOSB/FROST-Server#112]
I'm trying to conduct a spatial query using Datastream/observedArea however I'm getting the error:
Illegal operation: Could not convert parameter of type com.querydsl.core.types.dsl.StringOperation to type com.querydsl.spatial.GeometryExpression

I think I've tracked the problem down to lines 87, 106 of PropertyResolver class. E.g.: `addEntry(EntityProperty.OBSERVEDAREA, qDatastreamsClass, (ExpressionFactory<AbstractQDatastreams>) (AbstractQDatastreams qPath) -> qPath.observedArea.asText());`
Unlike Feature/feature and Location/location the observedArea resolver returns asText().

The need for this to work is low as I can filter spatially through Thing or FeatureOfInterest, though it would make sense for this to be available for filtering since it is there. I guess I'm a little confused at the purpose of the observedArea column as it isn't displayed in the Datastream response either.

Request URL: `/FROST-Server/v1.0/Datastreams?$filter=st_within(observedArea,geography%27POLYGON%20((143.52951049804688%20-37.974514992024595,%20144.08432006835935%20-37.974514992024595,%20144.08432006835935%20-37.6936010372444,%20143.52951049804688%20-37.6936010372444,%20143.52951049804688%20-37.974514992024595))%27)`

**Comment by hylkevds** [comment]
You're right, geo filters on Datastream/observedArea should work.

That it is not returned in a GET request is probably because if issue https://github.com/opengeospatial/sensorthings/issues/9 
The standard states that the item must be a Polygon, but for static sensors, it is usually just a point. Since it's not possible to cast a Point to a Polygon, FROST ends up returning nothing.

I think I'll change the code to just return the point in that case.

**Comment by hylkevds** [comment]
It's now fixed in the master branch
