### ISSUE TITLE
POST Thing with TaskingCapabilities

### ISSUE THREAD

**Issue by smilehappy126** [FraunhoferIOSB/FROST-Server#126]
Hi, 
    I've tested that POST Thing with TaskingCapabilities can be successful. However, the STA only give back this new THING's id in HTTP Response Header "location". I'm wondering if it's possible to return this new TaskingCapabilities with HTTP Response Header at the same POST action?
Thanks.

**Comment by hylkevds** [comment]
If you create a bunch of entities with a deep-insert, such as a thing, with datastreams, taskingcapabilities,etc., you only get the id of the top-level entity.

There is no real way around this, since there can be only one "location" Header. The only way to get the ids of the auto-created entities is by fetching them using GET requests.

**Comment by smilehappy126** [comment]
I see. It seems that if I want to get TaskingCapabilities ID, I have to send a new GET Request.
Thanks for answering.
