### ISSUE TITLE
[Question]empty Observations ?

### ISSUE THREAD

**Issue by mulderyu** [FraunhoferIOSB/FROST-Server#1261]
I got this result of:

`"Observations": [],`

does it means Observations has no resluts or I got something wrong?

**Comment by hylkevds** [comment]
It means there are no Observations.
Whether that's good or bad depends on what you're doing.

**Comment by mulderyu** [comment]
I'm wondering what's difference between this:
`"Observations": [],`
and this:
`"Observations": [
"phenomenonTime": NULL,
"result": NULL
],`

**Comment by hylkevds** [comment]
The first one is an EntityCollection with no Observations, the second an EntityCollection with an invalid Observation. Observations must always have a phenomenonTime, so the second case should never happen. result is allowed to be null, since there are cases where one wants to explicitly state that an Observation was attempted, but no result was generated.
