### ISSUE TITLE
Cleaning up your data...

### ISSUE THREAD

**Issue by rduivenvoorde** [FraunhoferIOSB/FROST-Server#127]
Experimenting here with Option 2 of modelling a driving car/thing with sensors:
https://github.com/opengeospatial/sensorthings/issues/33#issuecomment-350040053

So: creating 1 Thing, 1 Datastream, then a lot of Locations and Observations (which in turn create FeaturesOfInterest and HistoricalLocations)

Wanted to clean up a little so:
- Deleted the (one) Datastream I created, that (for what I think...) removed also the linked Observations
- Deleted the (one) Thing

But as I show the FeaturesOfInterest in a map (I created a 'proxy' which creates geojson from a FOI stream) I see I still have all FOI's (and also all HistoricalLocations).

So my question:
- is this by design? And should I have deleted the linked FOI's *first* (no sure based on what though)?
- or should I delete the HistoricalLocations first before removing the Thing.
- if so: what are the consequenses for the FOI's (as they are linked to HistoricalLocations I think)?

All talking here about cleaning up by the REST interface (or maybe the MQTT interface too) not about via Postgresql).

Or is there no vision yet about cleaning up?
My use case of a 'measurent'-journey would clutter up my map a lot, so it would be nice if there would be a nice interface to tell: "delete Thing 42 recursively".
In my other use-case (about 10.000.000 measurements per month) it would be ok to clean up oldest data after some months. 

Thanks for any suggestions.

**Comment by hylkevds** [comment]
After deleting the Thing, the HistoricalLocations should also be gone, since they have a foreign key relation to the Thing.
The Locations and FoIs will stay, since Locations can exist without Thing, and FoIs can exist without Observations.

Once the Observations and Thing are gone, cleaning up the Locations and FoIs is tricky, since you can not request all FoIs that have no Observations.

FROST-Manager has a Cleaner tab in the GUI that can delete all FoIs with no Observations, and all Locations with no Things. It does this by fetching all FoIs, with an expand on `Observations($select=id;$top=1)` and deleting those FoIs that return an empty Observations list.

If you want to do general data cleanup, and delete all Observations older than a certain date, FROST has an experimental extension that allows for DELETE on collections, with a filter. https://github.com/opengeospatial/sensorthings/issues/44

If you know for certain that all your FoIs have only one Observation, you can do:
`DELETE v1.0/FeaturesOfInterest?$filter=Observations/phenomenonTime lt now() sub duration'P1M'
`
to delete all FoIs that have Observations older than a month. This will then also delete the Observations.

Similarly, if you are certain that the Location entities are not re-used, you can delete all old Locations by doing
`DELETE v1.0/Locations?$filter=HistoricalLocations/time lt now() sub duration'P1M'
`
This will also delete the HistoricalLocations that belong to those Locations.

**Comment by rduivenvoorde** [comment]
Ah, thanks. Yes, I checked the database, all HistoricalLocations are gone: confirmed.

I can write a small python/bash/curl loop to do the cleanup as you describe the FROST-Manager is doing (cannot get FROST-Manager to show me something yet...).

The experimental functions do work to. Thanks!

**Comment by rduivenvoorde** [comment]
Will close this issue, but not without telling everybody that they should have a look at the FROST-Manager desktop application Hylke mentioned above:
https://github.com/FraunhoferIOSB/FROST-Manager
Easy to view/edit/delete/clean your data!! 
But: use java11 and to view something (after connecting to your FROST server... you have to push a button first (the little 'Download' one to the right)
