### ISSUE TITLE
Question: Why are you using Oracle Java?

### ISSUE THREAD

**Issue by kohlibri** [FraunhoferIOSB/FROST-Server#129]
Why are you using Oracle Java? 
Oracle java is no longer free from the beginning of next year.
I have good experiences with OpenJDK.

**Comment by phertweck** [comment]
To which Java version are you referring exactly?

The Travis-CI Build runs using "openjdk11". The docker images use "openjdk:8" and "tomcat:8-jre8", which are both based on OpenJDK. Anyhow we need to check if "tomcat:8-jre8" is still maintained, since this tag is not listed in the [official documentation](https://hub.docker.com/_/tomcat) any more.

**Comment by phertweck** [comment]
I think this issue is solved. If not, please reopen.
