### ISSUE TITLE
Ability to filter on absence of a property

### ISSUE THREAD

**Issue by gertvervaet** [FraunhoferIOSB/FROST-Server#1571]
I am trying to filter for all things that do not have a certain property , but there does not seem to be an operator or value to test for non existence. 
Tried https://<server>/v1.1/Things?$filter=length(properties/source) eq 0 but also that doesn't work.

**Comment by hylkevds** [comment]
That's a question that has come up before: #573.
FROST currently does not support the `null keyword.

**Comment by hylkevds** [comment]
Since version 2.1.3 FROST supports comparing to `null`:

[airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Things?$filter=properties/measurementRegime eq null](https://airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Things?$filter=properties/measurementRegime%20eq%20null)

[airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Things?$filter=properties/measurementRegime ne null](https://airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Things?$filter=properties/measurementRegime%20ne%20null)

**Comment by gertvervaet** [comment]
Cool, thanks!!
