### ISSUE TITLE
InternalMessageBus errors on fraunhoferiosb/frost-server-http

### ISSUE THREAD

**Issue by DanielBertocci** [FraunhoferIOSB/FROST-Server#1820]
I have noticed in FROST Server log a lot of these errors:

```log
ERROR  d.f.i.i.f.messagebus.InternalMessageBus - Failed to add message to queue. Increase the queue size to allow a bigger buffer, or increase the worker pool size to empty the buffer quicker
```

From the configuration settings I understand that the bus is used to _configure the way the HTTP and MQTT packages communicate with each other_.

I expected that the MQTT module wasn't present in the http version and despite the env variable **mqtt_Enabled** set to _false_ the error is present in the logs.

Any suggestions?

I am using fraunhoferiosb/frost-server-http:2.2 and checked on multiple versions and it happens there too.

**Comment by hylkevds** [comment]
There is always a MessageBus active, regardless if the MQTT module is active or not. Though obviously, when there are no listeners on the internal-only bus, we need to do some more optimisations :)

The two settings are: `bus.workerPoolSize` (default 2) and `bus.queueSize` (default 100)
Setting the queueSize to the size of the batches you import should fix the warnings.

**Comment by DanielBertocci** [comment]
Thank you for the clarification :)
If I increase those numbers though it uses more resources, doesn't it? I would prefer to keep that log if increasing the queue size could impact the performance ;)

**Comment by hylkevds** [comment]
I doubt you'd see a difference in performance, since it's just some threads that take each message and loop over all 0 subscribers. The logging has a lot bigger performance impact!

But I've implemented an improvement for it.

**Comment by ndevilleBE** [comment]
Good morning @hylkevds ,
Is there a way to 'clean' the message bus to stop the error being logged? 
I get this error message printed multiple times every milliseconds, which makes the logs unreadable (not mentioning the performance issue).  I downgraded the batch size to 100 (from 200) but it is not enough to solve the issue. 
Btw, I do not make use of MQTT at all so I don't need it. 
Thanks!

`09:32:36.242 [     IntBusPrc-2] WARN      d.f.i.i.f.mqtt.MqttManager - EntityChangedevent discarded because message queue is full 10! Increase mqtt.SubscribeMessageQueueSize and/or mqtt.SubscribeThreadPoolSize.`

**Comment by hylkevds** [comment]
Either (if you have mqtt turned off) upgrade to a version >= 2.2.1, or try doing what it suggests:
> Increase mqtt.SubscribeMessageQueueSize and/or mqtt.SubscribeThreadPoolSize.

And:
> Setting the queueSize to the size of the batches you import should fix the warnings.
