### ISSUE TITLE
FROST Server very slow on large requests

### ISSUE THREAD

**Issue by Mr-Pine** [FraunhoferIOSB/FROST-Server#1870]
Frost doesn't send a `Content-Length` Header for some GET Requests (I'm not quite sure when exactly, maybe if the request is too long? I could replicate it with `/v1.1/ObservedProperties?$expand=Datastreams` and `/v1.1/Tasks`)

This causes [FROST-Client](https://github.com/FraunhoferIOSB/FROST-Client) to considerably slow down for large requests: https://stackoverflow.com/a/13688379/11921893 (Problematic Frost code: https://github.com/FraunhoferIOSB/FROST-Client/blob/693da44b9dd87ad8c0a4befbe588207edde09d25/src/main/java/de/fraunhofer/iosb/ilt/sta/query/Query.java#L178). Decoding a Request with a Content-Length of ~2 Million takes several seconds.

**Comment by hylkevds** [comment]
FROST can't send a Content-Length Header because it doesn't know how long the content will be when the headers are sent. It stars sending data as soon as the data comes from the database. It doesn't first gather the entire response before sending it.

This actually makes things faster, not slower.

The problem with large responses and FROST-Client is that FROST-Client doesn't (yet) start decoding the response as soon as data is received, but instead waits for the entire response to be received before parsing it. Ideally in a background Thread so the application can start using the data while it comes in. That's also the core of the stackoverflow post: Don't put the entire response in a String first, but parse it directly from the stream...
It would be great if you could look into that :)

**Comment by Mr-Pine** [comment]
I investigated some more. Turns out I misinterpreted my debugging. Testing the request manually with curl revealed that the frost server itself is the problem:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3403k    0 3403k    0     0   176k      0 --:--:--  0:00:19 --:--:--  136k
```
Decoding doesn't seem to be the problem, curl vs redirecting (and doing some processing) via our backend using FROST-Client is almost the same speed.

**Comment by hylkevds** [comment]
FROST-Server can only be as fast as your database. Do you get log messages about slow queries? Are FROST and PostgreSQL running on the same machine? How is the CPU load of the machines involved? What disks are you using? There are many factors involved in performance...

**Comment by Mr-Pine** [comment]
Since I don't administrate these servers (they are running on the ilt k8s cluster (plasma)) I don't know the answer to most of these questions. But I can't really imagine that this is just an issue with DB speed as that doesn't really fit to typical DB performance...

**Comment by hylkevds** [comment]
Cloud instances are notorious for having bad database performance, since the default storage is often quite remote from the node that runs PostgreSQL. One must ensure the database is on local SSD disks to get decent speeds.
But without details there is nothing we can do to help, so I'll close this.
