### ISSUE TITLE
How is the Syntax for the MQTT Broker Username and Password?

### ISSUE THREAD

**Issue by rlhochpass** [FraunhoferIOSB/FROST-Server#251]
I use the All-In-One packet for docker(-compose) and I want to connect my FROST-Server to my MQTT Broker. 
In the documentation there are many settings but i don't find how i can configurate the MQTT Broker username and password in my .yaml-file.

**Comment by mjacoby** [comment]
If I understand you correctly, you want the FROST-Server to use an existing MQTT Broker for notification about changes. 

That is not possible, because the FROST-Server needs a rather low-level access to the MQTT Broker (e.g. know which subscriptions are actually present) to provide best performance. See https://github.com/FraunhoferIOSB/FROST-Server/issues/10#issuecomment-297933817 for a more detailed explanation. Therefore, the FROST-Server does not connect to an existing MQTT Broker for sending notifications but hosts its own one.

Maybe using an MQTT Bridge as discussed in the above mentioned issue might be a solution for you.

**Comment by rlhochpass** [comment]
Yes you understood that correctly. Based on the documentation, I was not really aware of this. Thank you for answer.

**Comment by hylkevds** [comment]
One addition to this:
If the MQTT broker you would like to use has a way of accessing the list of current subscriptions, and a way to subscribe to subscribe events, then it is possible to make an implementation of the `de.fraunhofer.iosb.ilt.frostserver.mqtt.MqttServer` interface that connects FROST to your broker instead of using the internal Moquette broker.
