### ISSUE TITLE
MQTT Publish new Thing, Datastreams ... etc

### ISSUE THREAD

**Issue by smilehappy126** [FraunhoferIOSB/FROST-Server#252]
Hi,
    I'm wondering if v1.0 support publish new Thing, Datastream and so on via MQTT? 
    `v1.0/Things`
    In my case, only publish new Observation has succeeded. If this isn't available, if there is a reason for not implement this 
    feature?
    Thanks!
Ru

**Comment by mjacoby** [comment]
The FROST-Server conforms to the [SensorThings API standard](http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#85) where it is defined that MQTT publish is only available for Observations.

I can't tell for sure know why this design decision has been made, but I could image that it was assumed that Observations are the only entity type that needs to be created with a high frequency so that MQTT would be preferred to HTTP. 

For further questions regarding the standard, I would like to point to the Github repository of the standard itself https://github.com/opengeospatial/sensorthings/issues. The standardization group is working von version 2.0 of the standard, which will probably include considerable changes to MQTT.

**Comment by smilehappy126** [comment]
@mjacoby  Thanks for the prompt reply. I see.
