### ISSUE TITLE
Filtering value with [ ] results in exception

### ISSUE THREAD

**Issue by DLade** [FraunhoferIOSB/FROST-Server#299]
If I tried to filter an object with a [ or ] in name I got the following error:

(version: fraunhoferiosb/frost-server:latest - 11 hours ago)
---
Message Invalid character found in the request target [/FROST-Server/v1.1/Things?$filter=name%20eq%20%27[hallo]%27]. The valid characters are defined in RFC 7230 and RFC 3986

Description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

Exception

java.lang.IllegalArgumentException: Invalid character found in the request target [/FROST-Server/v1.1/Things?$filter=name%20eq%20%27[hallo]%27]. The valid characters are defined in RFC 7230 and RFC 3986
	org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:504)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:503)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.base/java.lang.Thread.run(Thread.java:834)

**Comment by hylkevds** [comment]
You have to urlencode the `[` and `]` characters, since they are not allowed in URLs according to the stated specifications. The request is already rejected by Tomcat, so it never reaches FROST.

It does seem that there is a way to make Tomcat allow those characters any way, using the `relaxedQueryChars` parameter...

**Comment by DLade** [comment]
Thx, it works with URL-Encoding. I just wondered because it is inside a value (some objects has names with `[` `]`).

**Comment by hylkevds** [comment]
Yes, values in URLs should always be urlencoded if they contain special characters.

**Comment by ssoper-usgs** [comment]
I'm running into this issue as well, not because of any queries I'm launching against the frost api, but rather because a security scan our organization launches against it.  The scan picks up the resulting tomcat-level stack trace and flags it as a vulnerability.  I'm wondering if you have any pointers on how to add that `relaxedQueryChars` setting into the frost images (we use docker to deploy the http and mqtt images).  Thanks!

EDIT: This is a closed issue, I'll open a new one with more context.
