### ISSUE TITLE
MqttMessageBus - Failed to connect to broker

### ISSUE THREAD

**Issue by rchochpass** [FraunhoferIOSB/FROST-Server#360]
Hello,

I have a problem with my mqtt- / bus- configuration. 

My setup: 
I use a server on ubuntu 20.04. (LTS)
I've containerd the postgreSQL (with postgis extension) and PG-Admin and i use the MQTTP (HTTP+MQTT) in Tomcat. (the web-service must be in a tomcat)

When I start the tomcat, the http- services work, but i get no connection by using MQTT.

The log says that the FROST-Server can't connect to the MqttMessageBus - Broker.

This is my configuration: 
![grafik](https://user-images.githubusercontent.com/78138913/109305835-9818ce00-783e-11eb-9700-563f91594a67.png)

Does anyone see a mistake? I don't know what exactly I must configurate for MQTT and the bus in the tomcat deployment. (in docker it works but i need the tomcat-deployment)

In context of that I've a understanding question. Which role plays the "MessageBus". I understand this like a virtual simplex connection, which is triggered by new, deleted or updated observations. So the moquette-Broker knows that he must publish a new observation. Is this right or what function has the bus? 

Many thanks!

**Comment by hylkevds** [comment]
You are correct in the role the message bus plays. The message bus is used by separate frost components to communicate with each other. It is, for instance, used by a FROST-HTTP component to tell the FROST-MQTT components that it just inserted a new Observation, so that the MQTT components know they have to send a message to interested clients.

You've configured this _internal_ messageBus to use an (_external_) MQTT broker. However, when using the MQTTP (all-in-one) package, you don't need an external message bus, since all components run in the same Java Virtual Machine. You can use the default InternalMessageBus.

**Comment by rchochpass** [comment]
You mean the bus broker, right? What do I have to enter there in order to use the internal all-in-one packet?

Thank you very much for your effort.

**Comment by hylkevds** [comment]
See https://fraunhoferiosb.github.io/FROST-Server/settings/settings.html
`bus.busImplementationClass = de.fraunhofer.iosb.ilt.sta.messagebus.InternalMessageBus`
