### ISSUE TITLE
External MQTT Broker

### ISSUE THREAD

**Issue by Executioner1939** [FraunhoferIOSB/FROST-Server#426]
Hi, 

I would like to know if it's possible to use my external MQTT Broker, instead of running my own one as a part of the FROST deployment.

I am not sure if I am missing some configuration, all the options seem to be for configuring the provided MQTT Broker.

Your help is appreciated :-)

**Comment by hylkevds** [comment]
It's not possible to use an external broker for the same reason that bridging functionality can not realistically be used.
The hard part of MQTT in SensorThings API is dealing with large number of potential topics that all need to receive the same updates.

Take for instance an update to Datastream(1). Which topics need to be notified?
v1.0/Datastreams
v1.0/Datastreams(1)
v1.0/Things(1)/Datastreams
v1.0/Sensors(1)/Datastreams
v1.0/ObservedProperties(1)/Datastreams
v1.0/Observations(xxx)/Datastream (possibly millions of topics)

And each of those can have about 3 million different combinations of $select with the 10 properties of Datastream. Since $select is not part of MQTT, the MQTT broker can not do this processing for you.

That's why the broker is part of FROST-Server, so that FROST can keep track of which topics actually do have a subscription on them, so it only needs to send notifications to those. Whichever bridging or external broker solution you want to use will also need to forward the active subscriptions to FROST.

**Comment by Executioner1939** [comment]
I see, thank you very much for the explanation, I will close this now :-).
