### ISSUE TITLE
Filter with traditional Chinese parameter doesn't work

### ISSUE THREAD

**Issue by KuChiaChun** [FraunhoferIOSB/FROST-Server#53]
I have some columns in  traditional Chinese and I am trying to filter with it
Original Data in Table:
![ashampoo_snap_2018 5 11 _16h32m35s_001_](https://user-images.githubusercontent.com/25979667/39914917-f7fc6128-5538-11e8-8391-c12d5281fcb9.png)
 
Below is my url:
http://localhost:8080/STA/v1.0/Datastreams?$filter=name eq '水位高度'
Result:
Invalid query: Query is not valid: Lexical error at line 1, column 18.  Encountered: "\u6c34" (27700), after : "\'"

It seems that traditional Chinese character will be encoded to unicode by Explorer.
How do I deal with it?
Any suggestion will be appreciated. Thanks a lot.

**Comment by hylkevds** [comment]
That the characters are converted to Unicode is good. The problem was the query parser was not Unicode-aware.
I've fixed it in the master branch. If you have a self-compiled version and can't update to master yet, the fix is just a matter of setting the option `UNICODE_INPUT = true;` in queryParser.jjt.
