### ISSUE TITLE
FROST-Server safe for Log4shell?

### ISSUE THREAD

**Issue by rduivenvoorde** [FraunhoferIOSB/FROST-Server#671]
Hi, currently there is a lot of energy going into the log4j hacks for java server applications, see
https://logging.apache.org/log4j/2.x/security.html
and 
http://cve.mitre.org/cgi-bin/cvename.cgi?name=2021-44228

I could not find any other pointers that FROST-Server is using log4j2 then this line below:

```
FROST-Server.MQTT.Moquette/pom.xml: <artifactId>slf4j-log4j12</artifactId> 
```

It would be good if there was a confirmation that FROST-Server is indeed not affected.

Thanks!

**Comment by hylkevds** [comment]
The short version: FROST-Server (and the other related projects) is not vulnerable, since it doesn't use Log4J.

FROST-Server uses slf4j as an abstract logging framework, with Logback as the implementation.

The Moquette MQTT broker also uses slf4j, but with Log4J as the implementation. Since we can't have two logging implementations, the line in `FROST-Server.MQTT.Moquette/pom.xml` **excludes** `slf4j-log4j12` as a dependency, and with it Log4J.

Tomcat also does not use Log4J, but Apache Commons Logging, in combination with java.utils.logging.

**Comment by MVennebusch** [comment]
Hi, I have another question related to log4j:
Our log4j-checker found some files that seem to use/contain log4j (see screenshot). Do you think this is critical?
![sensorthingsapt_172 16 1 26](https://user-images.githubusercontent.com/80272196/147949959-e7d42ad4-c5c6-4050-b1bb-1e308a69ec8b.png)
Thanks a lot!

**Comment by hylkevds** [comment]
Can you make that tool list the files that it thinks belong to Log4j? It is unlikely that these jars actually have any Log4j code.

**Comment by MVennebusch** [comment]
We tried to get more information, but unfortunately it is not possible. Then please simply consider our comment as a hint. May be it is a "false alarm"...

**Comment by hylkevds** [comment]
These jars contain bridges to/from Log4J, and as such contain files with `Log4J` as part of their name. They do not actually contain Log4J code. False positives fortunately.
