### ISSUE TITLE
MQTT clients receive observations out of order (or dropped)

### ISSUE THREAD

**Issue by ch08532** [FraunhoferIOSB/FROST-Server#836]
We have noticed that our clients seem to not receive MQTT observations always in the correct order (or sometimes do not receive observations).  We are using the standard MQTT Paho library in our nodejs service.  We are using FROST version 1.14.1 and have not changed any of the MQTT defaults.  

We have one process that creates observations using the REST interface at a rate of 10-20Hz.  That seems fine.  However, on the consumer side the MQTT listener of those observations at time can receive messages out of order or in some cases dropped all together. We have noticed the incidence of this issue is much more frequent in the first several seconds of data (for us around 180 observations) before it becomes far less prevalent.

Any suggestions on how to resolve this or has this been observed before?  Would this be related to the MQTT QoS settings?

**Comment by hylkevds** [comment]
The order of messages is not fixed in MQTT, they can arrive in any order.

At QoS level 0 the broker tries to deliver a message once. If that fails, the message is dropped.
At QoS level 1, the broker retires until the client acknowledges the message. This means a client can receive the same message multiple times, but the message will be delivered.
At QoS level 2, there is an extra ack to avoid the double delivery.

So you should use at least QoS 1.
