### ISSUE TITLE
Wildcards not allowed

### ISSUE THREAD

**Issue by geoxanadu** [FraunhoferIOSB/FROST-Server#9]
You mentioned that wildcards are not allowed when using MQTT. However, I thought that wildcards would be allowed following the ISO MQTT specification. Is this planned in future implementations?

**Comment by hylkevds** [comment]
Section [14.2](http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#89) lists the topics that are supported by the standard and there wildcards are not included.

Now, I suppose you want wildcard support because a subscription on v1.0/Observations is pretty useless, since you don't know the Datastream of the newly created Observations, while v1.0/+/Observations would in theory give you the Datastream id in the topic. Am I right?

I think this would be best discussed on the SensorThings API github: https://github.com/opengeospatial/sensorthings
