### ISSUE TITLE
MqttManager doesn't allow subscription to topics in the $SYS hierarchy 

### ISSUE THREAD

**Issue by DrAyoub** [FraunhoferIOSB/FROST-Server#936]
Hi,

I'm looking to monitor Frost MQTT broker through Mosquitto Exporter to collect $SYS topic metric for Prometheus system, but I found that mqttManager does not permit subscription.

`Subscription to topic '$SYS/#' is invalid. Reason: topic must start with a version number.`

**Comment by mjacoby** [comment]
FROST does not support the $SYS topic. This is because it is not part of the MQTT specification and also not implemented in the MQTT server library FROST uses.

As is it [discouraged to use $SYS topic for monitoring](https://www.hivemq.com/blog/why-you-shouldnt-use-sys-topics-for-monitoring/), especially in production environments, I currently see no particular reason to add this feature to FROST.

**Comment by hylkevds** [comment]
FROST-Server.MQTT does not use Mosquitto for the public-facing broker, it uses Moquette. Moquette does not publish statistics to $SYS.

**Comment by DrAyoub** [comment]
Are there any alternatives to monitor FROST MQTT broker ?

My end goal is to get the total number of 'PUBLISH' messages received that exist in subject[ '$SYS/broker/messages/received' ](https://mosquitto.org/man/mosquitto-8.html)and compare it with the number of 'Observations' in the database to detect if there is a loss of messages.

**Comment by hylkevds** [comment]
The only way for Observations that are published on the MQTT interface to be lost, is when the publish-queue is overrun. When that happens, this is logged.
You can get additional queue status information by setting [`queueLoggingInterval`](https://fraunhoferiosb.github.io/FROST-Server/settings/settings.html#general-settings) to a positive number of milliseconds.
If you monitor your logs, you'll be notified when messages are lost.

**Comment by DrAyoub** [comment]
@hylkevds 
It's ok, I'll use the log to detect if there is a loss of Observations.
FROST uses Mosquitto as an internal MQTT broker and Mosquitto support broker status topics. Why not leave this feature in FROST.

**Comment by hylkevds** [comment]
FROST-Server uses Mosquitto (or any other MQTT broker) as internal _message bus_, not as external-facing broker. The external-facing broker is an embedded Moquette. Since FROST needs to know exactly on which topics subscriptions exist, and that is easiest when the broker is also implemented in Java.
